all:
	#g++ -I /usr/include/c++/5/bits rbtree-test.cpp
	#linux compile include sgi-stl headers
	#g++ -I ../../stl  rbtree-test.cpp
	# window compile program include sgi-stl headers
	g++  -D__STL_USE_NEW_IOSTREAMS -U__STL_THREADS -I ../../stl  rbtree-test.cpp 

